#!/usr/bin/env python3
"""Create the error_analysis table in Supabase if it doesn't exist."""
import os
from dotenv import load_dotenv
from supabase import create_client

load_dotenv()

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_ESL_KEY")

SQL = """
CREATE TABLE IF NOT EXISTS public.error_analysis (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id text NOT NULL,
  submission_date timestamptz NOT NULL DEFAULT now(),
  class text NOT NULL,
  name text NOT NULL,
  error_percent integer NOT NULL,
  summary text NOT NULL
);
"""


def main():
    if not SUPABASE_URL or not SUPABASE_KEY:
        print("Error: SUPABASE_URL and SUPABASE_ESL_KEY must be set")
        return

    client = create_client(SUPABASE_URL, SUPABASE_KEY)
    try:
        client.rpc("exec_sql", {"sql": SQL}).execute()
        print("error_analysis table ready")
    except Exception:
        # rpc may not be available — try direct query
        try:
            result = client.table("error_analysis").select("*").limit(1).execute()
            print(f"error_analysis table exists ({len(result.data)} rows)")
        except Exception as e2:
            print(f"Cannot create table via client: {e2}")
            print("Create manually via Supabase dashboard SQL editor:")
            print(SQL)


if __name__ == "__main__":
    main()
